// app/layout.tsx

import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import LayoutWrapper from "./LayoutWrapper"; // ← 아래에 따로 만듦

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* scroll restoration 비활성화 */}
        <script dangerouslySetInnerHTML={{
          __html: `window.history.scrollRestoration = 'manual'`
        }} />

        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
